# Generated by Django 4.0.6 on 2022-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_rank_crypto_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
